"""
Question 1 of Rosalind BINF Stronghold

Named 'DNA' on the tree view of topic.

Given: A DNA string s of length at most 1000 nt.
Return: Four integers (separated by spaces) counting the respective number
of times that the symbols 'A', 'C', 'G', and 'T' occur in s.
"""

# Sample Dataset
#instring = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"

# Want the output:
# '20 12 17 21'


instring = "CTGGGGCCGACGCGACCACGTCGGTCCTCACCAAACCATGGACCAGGTTTCCCGGGGTGCTGGTGTTATCACTAAGCTCAGACACATCTGTATACTGTCTATTCGAGAATTAAGGTATGGACGTACCCGCACTTGCGGTACTACATTCAATCGATAATGCAGCGAGAGATCGGTTACGAGCCCTACGCGCCGCGCGCCTGTACCCGCAAGCGCACCGGAAAGACATGGTACAGCCCGTCACCAGAGTCGAACCAGCCCCTCGCCGTACCATGCTCTACGGTGACTACTAGTTAGGACGCGCACACGGGGGCTGTTGTTGCTGGCCTGCATAAGATGAGTTCGGAGGCAACGTGGGAATTTTGTTCTGGATCTATCCGATGCGATGCGGGGTGCCTATCGTATTCCACCCAACTACGTTCCAGCGCTATCAGAATTCTTTGGTACGCCCTGTAATTTGCTAACTCCGCTATTAGTTTGGGACCGTGTCCAGGATCCTGTGTGGTGCAGGGAGTGATGCGAACTCATAGGACTATAACACTACGATATGGAGGCCTCAATGCAGGCTGATTCGTTGCTTGCCGGTGCAAAAGTAGACGTCTACCCTCTTTACAGCATCTATTAAGCGTGTAACATAGTTTACATTAAGATATACATCATCCATTTTGAACGTTCCTATCGCCATGACTCAGTCGCTCTGGTTTCTATGGATGAATATCCGATTGGTTGATTGTAAATTAGGCAGGATGAGACATCTCTGATACAGCGGACTCACTAGCGTGTAGAACTACTGGCTGTATTCACTCTACAGTGAGCAGTCCACTCAGTG"

bases = {'A': 0, 'C': 0, 'G': 0, 'T': 0}

for base in bases:
    for char in instring:
        if base == char:
            bases[base] += 1

#loop = [print(value) for value in bases.values()]
print(f"{bases['A']} {bases['C']} {bases['G']} {bases['T']}")
#for k, v in bases.items():
    #print(v)
